server:
  port: 8080

watchmode:
  api:
    base-url: https://api.watchmode.com/v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    com.watchmode: DEBUG
